workspace_root: &workspace_root ~/product-suite

attach_workspace: &attach_workspace
  attach_workspace:
    at: *workspace_root

defaults: &defaults
  working_directory: *workspace_root
  docker:
    - image: circleci/node:10

version: 2

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ .Branch }}
            - dependencies-master
      - run: npm install
      - run: npm run bootstrap
      - save_cache:
          key: dependencies-{{ .Branch }}
          paths:
            - node_modules
            - applications/app1/node_modules
            - applications/app2/node_modules
            - applications/api1/node_modules
            - packages/package1/node_modules
            - packages/package2/node_modules
            - packages/package3/node_modules
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .
  lint_changes:
    <<: *defaults
    steps:
      - *attach_workspace
      - run: npm run lint:changes
  test_changes:
    <<: *defaults
    steps:
      - *attach_workspace
      - run: npm run test:changes
  build_changes:
    <<: *defaults
    steps:
      - *attach_workspace
      - run: npm run build:changes
  publish:
    <<: *defaults
    steps:
      - *attach_workspace
      - run: 
          command: |
            mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - run: npm run publish
  docker:
    <<: *defaults
    steps:
      - *attach_workspace
      - setup_remote_docker
      - run:
          name: "Build and upload docker images to DockerHub"
          command: ./.circleci/buildDocker.sh
  release:
    <<: *defaults
    steps:
      - *attach_workspace
      - run: 
          command: |
            mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - run: npm run release
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - install
      - lint_changes:
          requires:
            - install
      - test_changes:
          requires:
            - install
      - build_changes:
          requires:
            - install
      - publish:
          requires:
            - lint_changes
            - test_changes
            - build_changes
          filters:
            branches:
              only: master
      - docker:
          requires:
            - lint_changes
            - test_changes
            - build_changes
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /\w@\d{1,}\.\d{1,}\.\d{1,}/
