workspace_root: &workspace_root ~/monotest

attach_workspace: &attach_workspace
  attach_workspace:
    at: *workspace_root

defaults: &defaults
  working_directory: *workspace_root
  docker:
    - image: circleci/node:10

version: 2

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ .Branch }}
            - dependencies-master
      - run: npm install
      - run: npm run bootstrap
      - save_cache:
          key: dependencies-{{ .Branch }}
          paths:
            - node_modules
            - applications/app1/node_modules
            - applications/app2/node_modules
            - applications/api1/node_modules
            - packages/package1/node_modules
            - packages/package2/node_modules
            - packages/package3/node_modules
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .
  lint_changes:
    <<: *defaults
    steps:
      - *attach_workspace
      - run: npm run lint:changes
  test_changes:
    <<: *defaults
    steps:
      - *attach_workspace
      - run: npm run test:changes
  build_changes:
    <<: *defaults
    steps:
      - *attach_workspace
      - run: npm run build:changes
  publish:
    <<: *defaults
    steps:
      - *attach_workspace
      - add_ssh_keys:
          fingerprints:
            - "98:77:18:01:dd:5b:ae:f6:ce:89:ba:da:73:e8:7a:a1"
      - run: ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run: npm run lint:release
      - run: npm run test:release
      - run: npm run build:release
      - run: echo $CIRCLE_REPOSITORY_URL
      - run: git config user.email "test@example.com"
      - run: git config user.name "CircleCi"
      - run: npm run publish
  docker:
    <<: *defaults
    steps:
      - *attach_workspace
      - setup_remote_docker
      - run:
          name: "Build and upload docker images to DockerHub"
          command: ./.circleci/buildDocker.sh
  release:
    <<: *defaults
    steps:
      - *attach_workspace
      - run: 
          command: |
            mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - run: npm run release
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - install
      - lint_changes:
          requires:
            - install
          filters:
            branches:
              ignore: master
      - test_changes:
          requires:
            - install
          filters:
            branches:
              ignore: master
      - build_changes:
          requires:
            - install
          filters:
            branches:
              ignore: master
      - publish:
          requires:
            - install
          filters:
            branches:
              only: master
      - docker:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /(.*)@(\d{1,}\.\d{1,}\.\d{1,})/
